export const routes = {
  main: '/',
  login: '/login',
  register: '/register',
  terms: '/terms',
  faq: '/faq',
  restore: '/restore',
  changePassword: '/changepassword',
  balanceHistory: '/history',
  account: '/account',
  visibility: '/visibility',
  criteria: '/criteria',
  statistic: '/statistic',
  finance: '/finance',
  notifications: '/notifications',
  blacklist: '/blacklist',
  friends: '/friends',
  messages: '/messages',
  postCreate: '/post_create',
};
