export { default as ArrowIcon } from './icons/arrow.svg?react';
export { default as AudIcon } from './icons/aud.svg?react';
export { default as AudioIcon } from './icons/audio.svg?react';
export { default as BackIcon } from './icons/back.svg?react';
export { default as ChatIcon } from './icons/chat.svg?react';
export { default as CheckIcon } from './icons/check.svg?react';
export { default as Check1Icon } from './icons/check1.svg?react';
export { default as ChecksIcon } from './icons/checks.svg?react';
export { default as CloseIcon } from './icons/close.svg?react';
export { default as CompressIcon } from './icons/compress.svg?react';
export { default as DotsIcon } from './icons/dots.svg?react';
export { default as FullscreenIcon } from './icons/fullscreen.svg?react';
export { default as HomeIcon } from './icons/home.svg?react';
export { default as LikeIcon } from './icons/like.svg?react';
export { default as LockIcon } from './icons/lock.svg?react';
export { default as LockbIcon } from './icons/lockb.svg?react';
export { default as LockcIcon } from './icons/lockc.svg?react';
export { default as LogoIcon } from './icons/logo.svg?react';
export { default as MessIcon } from './icons/mess.svg?react';
export { default as MessageIcon } from './icons/message.svg?react';
export { default as NormalIcon } from './icons/normal.svg?react';
export { default as NotifyIcon } from './icons/notify.svg?react';
export { default as PauseIcon } from './icons/pause.svg?react';
export { default as PenIcon } from './icons/pen.svg?react';
export { default as PhIcon } from './icons/ph.svg?react';
export { default as PhotoIcon } from './icons/photo.svg?react';
export { default as PhtoIcon } from './icons/phto.svg?react';
export { default as PlayIcon } from './icons/play.svg?react';
export { default as PlusIcon } from './icons/plus.svg?react';
export { default as PresentIcon } from './icons/present.svg?react';
export { default as RepostIcon } from './icons/repost.svg?react';
export { default as RightIcon } from './icons/right.svg?react';
export { default as SearchIcon } from './icons/search.svg?react';
export { default as Search2Icon } from './icons/search2.svg?react';
export { default as SetIcon } from './icons/set.svg?react';
export { default as SettingsIcon } from './icons/settings.svg?react';
export { default as Settings1Icon } from './icons/settings1.svg?react';
export { default as SmallcheckIcon } from './icons/smallcheck.svg?react';
export { default as SmallplayIcon } from './icons/smallplay.svg?react';
export { default as SmileIcon } from './icons/smile.svg?react';
export { default as SpeakerIcon } from './icons/speaker.svg?react';
export { default as TopIcon } from './icons/top.svg?react';
export { default as UserIcon } from './icons/user.svg?react';
export { default as UsersIcon } from './icons/users.svg?react';
export { default as VidIcon } from './icons/vid.svg?react';
export { default as VideoIcon } from './icons/video.svg?react';
export { default as VolumeIcon } from './icons/volume.svg?react';

import img1 from './images/1.jpg';
import img150 from './images/150.jpg';
import img2 from './images/2.jpg';
import img3 from './images/3.jpg';
import img4 from './images/4.jpg';
import img6 from './images/6.png';
import img78 from './images/78.png';
import img81 from './images/81.png';
import img97 from './images/97.png';
import anna from './images/anna.jpg';
import avatar from './images/avatar.jpg';
import avva from './images/avva.jpg';
import cat from './images/cat.jpg';
import placeholder from './images/placeholder.jpg';
import user from './images/user.jpg';

export { img1, img150, img2, img3, img4, img6, img78, img81, img97, anna, avatar, avva, cat, placeholder, user };
